<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var common\models\DeSailors $model */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'De Sailors'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="de-sailors-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'eligibility_info_id',
            'app_unique_id',
            'candidate_designation',
            'candidate_type',
            'center_id',
            'batch_id',
            'batch_config_id',
            'exam_date',
            'exam_group',
            'serial_generate_date',
            'serial_no',
            'eligible_district',
            'district',
            'name',
            'father_name',
            'father_nid',
            'father_occupation',
            'father_income',
            'mother_name',
            'mother_occupation',
            'current_village',
            'current_word_no',
            'current_union',
            'current_post_office',
            'current_thana',
            'current_post_code',
            'current_district',
            'current_phone',
            'permanent_village',
            'permanent_union',
            'permanent_word_no',
            'permanent_post_office',
            'permanent_thana',
            'permanent_district',
            'permanent_post_code',
            'permanent_phone',
            'guardian_name',
            'guardian_relation',
            'guardian_occupation',
            'guardian_address',
            'dob',
            'age_according_to_circular',
            'religion',
            'gender',
            'marital_status',
            'nationality',
            'photo',
            'qr_photo',
            'jsc_reg_no',
            'jsc_institute_name',
            'jsc_passing_year',
            'jsc_gpa',
            'ac_type_ssc',
            'ssc_institute',
            'ssc_group',
            'ssc_edu_board',
            'ssc_reg_no',
            'ssc_roll_no',
            'ssc_passing_year',
            'ssc_additional_subject',
            'ssc_gpa',
            'hsc_or_diploma',
            'hsc_dip_institute',
            'hsc_dip_group',
            'hsc_dip_board',
            'hsc_dip_reg_no',
            'hsc_dip_roll_no',
            'hsc_dip_passing_year',
            'hsc_dip_additional_subject',
            'hsc_dip_gpa',
            'ssc_edu_data:ntext',
            'hsc_edu_data:ntext',
            'ssc_teletalk_data:ntext',
            'hsc_teletalk_data:ntext',
            'experience_one_institute',
            'experience_one_subject',
            'experience_one_year',
            'experience_one_cert_name',
            'experience_two_institute',
            'experience_two_subject',
            'experience_two_year',
            'experience_two_cert_name',
            'experience_three_institute',
            'experience_three_subject',
            'experience_three_year',
            'experience_three_cert_name',
            'experience_four_institute',
            'experience_four_subject',
            'experience_four_year',
            'experience_four_cert_name',
            'is_freedom_fighter',
            'freedom_fighter_relation',
            'is_child_of_naval_officer',
            'naval_father_name',
            'is_departmental_candidate',
            'naval_office_no',
            'naval_rank',
            'navy_ship_etbd_retired',
            'naval_uniform_civil',
            'is_anser_vdp',
            'anser_vdp_rank',
            'anser_vdp_office_no',
            'is_khudro_jati_gosti',
            'phase',
            'payment_type',
            'is_manula_paid',
            'ref_id',
            'validation_id',
            'order_id_original',
            'amount',
            'store_amount',
            'card_type',
            'card_no',
            'trans_date',
            'payment_api:ntext',
            'payment_status',
            'referred_by',
            'reference_details:ntext',
            'have_reference',
            'relationship:ntext',
            'is_online_manual',
            'created_by',
            'updated_by',
            'created_dt',
            'updated_dt',
            'application_status',
        ],
    ]) ?>

</div>
